# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='birthday',
            field=models.CharField(max_length=10),
        ),
    ]
