# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_tracker', '0004_auto_20171014_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='birthday',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
