# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_tracker', '0005_auto_20171014_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
