# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_tracker', '0006_gift_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='gift',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='idea_tracker.Recipient'),
        ),
    ]
